#!/usr/bin/env python3
"""Build supplemental practical information tables for the ICML 2026 guide."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "data" / "processed"
PRACTICAL_OUT = OUT_DIR / "icml2026_practical_info.csv"
CHECKLIST_OUT = OUT_DIR / "icml2026_pretrip_checklist.csv"
BACKLOG_OUT = OUT_DIR / "icml2026_collection_backlog.csv"
LOCAL_ESSENTIALS_OUT = OUT_DIR / "icml2026_local_essentials.csv"
ONSITE_OPPORTUNITIES_OUT = OUT_DIR / "icml2026_onsite_opportunities.csv"


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        raise RuntimeError(f"No rows for {path}")
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def practical_info() -> list[dict[str, str]]:
    return [
        {
            "category": "official_schedule",
            "item_zh": "ICML 周结构",
            "item_en": "ICML week structure",
            "date_or_time_kst": "2026-07-06 Expo/Tutorial; 2026-07-07 to 2026-07-09 Main Conference; 2026-07-10 to 2026-07-11 Workshops",
            "location_zh": "COEX 会展中心",
            "location_en": "COEX Convention & Exhibition Center",
            "action_zh": "把 7 月 6 日当作熟悉场馆和 Expo/Tutorial 的导览日；7-9 日主攻主会，10-11 日按 workshop 主题拆分。",
            "action_en": "Treat July 6 as orientation plus Expo/Tutorial day; prioritize main conference July 7-9 and split July 10-11 by workshop themes.",
            "source_name": "ICML 2026 home",
            "source_url": "https://icml.cc/",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "Official page confirms dates and day grouping.",
        },
        {
            "category": "badge_access",
            "item_zh": "Registration Desk 时间和入口",
            "item_en": "Registration Desk hours and access",
            "date_or_time_kst": "Jul 5 14:00-19:30; Jul 6 07:00-18:00; Jul 7-9 07:30-18:00; Jul 10 07:30-16:00; Jul 11 07:30-12:00",
            "location_zh": "Hall B Foyer, East Gate",
            "location_en": "Hall B Foyer, East Gate",
            "action_zh": "首日先到 Hall B Foyer 取胸牌；workshop-only badge 可从 7 月 9 日 16:00 开始领取。",
            "action_en": "Go to Hall B Foyer first for badge pickup; workshop-only badges can be picked up starting July 9 at 16:00.",
            "source_name": "ICML virtual site / registration calendar",
            "source_url": "https://icml.cc/virtual/2026/calendar?filter_events=Registration%20Desk&filter_rooms=",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "yes",
            "notes": "Queue layout and final onsite access path should be checked on arrival.",
        },
        {
            "category": "badge_access",
            "item_zh": "注册二维码和胸牌字段",
            "item_en": "Registration QR code and badge fields",
            "date_or_time_kst": "",
            "location_zh": "注册台",
            "location_en": "Registration desk",
            "action_zh": "确认注册邮箱可访问；姓名、机构会印在胸牌上；二维码用于现场 check-in。",
            "action_en": "Make sure the registration email is accessible; first name, last name, and institution print on the badge; QR code is used for check-in.",
            "source_name": "ICML registration page",
            "source_url": "https://icml.cc/Register/view-registration",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "Registration receipt and QR code are emailed to the address in the profile.",
        },
        {
            "category": "badge_access",
            "item_zh": "胸牌是入场凭证",
            "item_en": "Badge is required for entry",
            "date_or_time_kst": "",
            "location_zh": "全会场",
            "location_en": "All conference areas",
            "action_zh": "离开酒店前检查胸牌；离开会场后可取下胸牌，避免暴露参会者身份。",
            "action_en": "Check badge before leaving the hotel; remove it offsite to avoid advertising attendee status.",
            "source_name": "ICML FAQ",
            "source_url": "https://icml.cc/FAQ",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "FAQ says attendees will not be allowed into the conference without a badge and includes safety advice.",
        },
        {
            "category": "badge_access",
            "item_zh": "胸牌补办规则",
            "item_en": "Badge replacement policy",
            "date_or_time_kst": "",
            "location_zh": "注册台",
            "location_en": "Registration desk",
            "action_zh": "第一次丢失可能需按剩余会议全价重买；24 小时内带两张胸牌回注册台可退款；第二次不退款。",
            "action_en": "First replacement may require buying a new registration for remaining sessions; refund is possible if both badges are returned within 24 hours; second replacement has no refund.",
            "source_name": "ICML FAQ",
            "source_url": "https://icml.cc/FAQ",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "Damaged or updated badges can be replaced for free.",
        },
        {
            "category": "badge_access",
            "item_zh": "胸牌不可共享",
            "item_en": "No badge sharing",
            "date_or_time_kst": "",
            "location_zh": "注册台 / 会场入口",
            "location_en": "Registration desk / venue entry",
            "action_zh": "不要转让或借用 badge；check-in 可能核对 ID 或学生证。",
            "action_en": "Do not transfer or lend badges; check-in may require ID or student ID matching registration.",
            "source_name": "ICML FAQ",
            "source_url": "https://icml.cc/FAQ/TransferRegistration",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "Registration is non-transferable and misuse can void registration.",
        },
        {
            "category": "badge_access",
            "item_zh": "学生注册需学生证",
            "item_en": "Student registration requires student ID",
            "date_or_time_kst": "",
            "location_zh": "注册 / check-in",
            "location_en": "Registration / check-in",
            "action_zh": "学生价参会者带实体或数字学生证；指南里放到行前清单。",
            "action_en": "Student-rate attendees should carry student ID; include this in the pre-trip checklist.",
            "source_name": "ICML FAQ",
            "source_url": "https://icml.cc/FAQ",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "FAQ says student ID is required at registration and check-in.",
        },
        {
            "category": "conference_tools",
            "item_zh": "Virtual site / Conference site",
            "item_en": "Virtual site / Conference site",
            "date_or_time_kst": "",
            "location_zh": "ICML 网站",
            "location_en": "ICML website",
            "action_zh": "用官方站保存 bookmark、下载/订阅个人日程；建议会前导出或离线保存重点 session。",
            "action_en": "Use the official site to save bookmarks and download/subscribe to personal schedules; export or save key sessions offline before arrival.",
            "source_name": "ICML virtual site",
            "source_url": "https://icml.cc/virtual/2026/index.html",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "The official site recommends JavaScript, a Chromium-based browser, and about 10 Mbps inbound bandwidth for full use.",
        },
        {
            "category": "onsite_services",
            "item_zh": "Help Desk",
            "item_en": "Help Desk",
            "date_or_time_kst": "Same hours as registration desk",
            "location_zh": "Hall B Foyer",
            "location_en": "Hall B Foyer",
            "action_zh": "把 Hall B Foyer 作为现场问题、失物、方向确认的第一站。",
            "action_en": "Use Hall B Foyer as the first stop for onsite questions, lost items, and directions.",
            "source_name": "ICML At the Conference",
            "source_url": "https://icml.cc/Conferences/2026/AtTheConference",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "yes",
            "notes": "Registration desk exact hours still need onsite/app confirmation.",
        },
        {
            "category": "onsite_services",
            "item_zh": "First Aid / Medical Office",
            "item_en": "First Aid / Medical Office",
            "date_or_time_kst": "",
            "location_zh": "靠近 Hall A4 的 West Gate Entrance",
            "location_en": "Near West Gate Entrance by Hall A4",
            "action_zh": "轻微医疗需求和紧急情况先去医疗办公室；现场也有流动 EMT/医疗人员。",
            "action_en": "For minor medical needs or emergencies, go to the medical office; EMT/medical staff also circulate in the venue.",
            "source_name": "ICML At the Conference",
            "source_url": "https://icml.cc/Conferences/2026/AtTheConference",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "",
        },
        {
            "category": "onsite_services",
            "item_zh": "Lost and Found",
            "item_en": "Lost and Found",
            "date_or_time_kst": "",
            "location_zh": "Hall B Foyer 的 Help Desk",
            "location_en": "Help Desk in Hall B Foyer",
            "action_zh": "失物先去 Hall B Foyer；贵重物品仍按个人保管处理。",
            "action_en": "Check Hall B Foyer first for lost items; still treat valuables as personal responsibility.",
            "source_name": "ICML At the Conference",
            "source_url": "https://icml.cc/Conferences/2026/AtTheConference",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "ICML page states ICML staff and COEX are not liable for lost, damaged, or stolen items.",
        },
        {
            "category": "onsite_services",
            "item_zh": "行李和衣帽寄存",
            "item_en": "Luggage and coat check",
            "date_or_time_kst": "Jul 6 07:30-19:30; Jul 7-9 08:00-19:30; Jul 10-11 07:30-17:30",
            "location_zh": "2F Plaetz 内",
            "location_en": "2nd floor inside the Plaetz",
            "action_zh": "到达日和退房后可优先利用；注意 7 月 10-11 日较早关闭。",
            "action_en": "Use it on arrival or post-checkout days; note the earlier closing time on July 10-11.",
            "source_name": "ICML At the Conference",
            "source_url": "https://icml.cc/Conferences/2026/AtTheConference",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "",
        },
        {
            "category": "onsite_services",
            "item_zh": "祈祷室",
            "item_en": "Prayer rooms",
            "date_or_time_kst": "",
            "location_zh": "Men: 2F ASEM 211; Women: 2F ASEM 207",
            "location_en": "Men: 2F ASEM 211; Women: 2F ASEM 207",
            "action_zh": "在地图/会场服务页单独标注，减少现场询问成本。",
            "action_en": "Mark these separately in the venue services section to reduce onsite friction.",
            "source_name": "ICML At the Conference",
            "source_url": "https://icml.cc/Conferences/2026/AtTheConference",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "include",
            "needs_recheck": "no",
            "notes": "",
        },
        {
            "category": "onsite_services",
            "item_zh": "Gender-neutral restroom",
            "item_en": "Gender-neutral restroom",
            "date_or_time_kst": "",
            "location_zh": "3F Auditorium 右侧洗手间",
            "location_en": "3rd floor restrooms on the right-hand side of the Auditorium",
            "action_zh": "在无障碍/包容性信息下标注。",
            "action_en": "Include under accessibility and inclusion notes.",
            "source_name": "ICML At the Conference",
            "source_url": "https://icml.cc/Conferences/2026/AtTheConference",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "include",
            "needs_recheck": "no",
            "notes": "",
        },
        {
            "category": "accessibility",
            "item_zh": "无障碍洗手间和轮椅租借",
            "item_en": "Accessible restrooms and wheelchair rental",
            "date_or_time_kst": "",
            "location_zh": "COEX 1F/2F/3F/4F；轮椅可在 1F West Gate 旁 Safety Situation Room 和 East Gate Information Desk 租借",
            "location_en": "COEX 1F/2F/3F/4F; wheelchairs at the Safety Situation Room near West Gate on 1F and the Information Desk by East Gate",
            "action_zh": "需要无障碍支持者提前邮件联系 inclusion-accessibility-chairs@icml.cc。",
            "action_en": "Attendees with onsite needs should email inclusion-accessibility-chairs@icml.cc ahead of time.",
            "source_name": "ICML At the Conference",
            "source_url": "https://icml.cc/Conferences/2026/AtTheConference",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "ICML page lists counts of accessible restrooms by floor.",
        },
        {
            "category": "accessibility",
            "item_zh": "Nursing rooms",
            "item_en": "Nursing rooms",
            "date_or_time_kst": "",
            "location_zh": "COEX 2F ASEM 209；Starfield COEX Mall 内另有 Agasarangbang rooms",
            "location_en": "COEX 2F ASEM 209; additional Agasarangbang rooms in Starfield COEX Mall",
            "action_zh": "放入亲子/照护信息。",
            "action_en": "Include in family and care logistics.",
            "source_name": "ICML At the Conference",
            "source_url": "https://icml.cc/Conferences/2026/AtTheConference",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "include",
            "needs_recheck": "no",
            "notes": "",
        },
        {
            "category": "conference_tools",
            "item_zh": "会场 Wi-Fi 风险",
            "item_en": "Venue Wi-Fi risk",
            "date_or_time_kst": "",
            "location_zh": "COEX，尤其 plenary/crowded areas",
            "location_en": "COEX, especially plenary/crowded areas",
            "action_zh": "提前下载 app、离线保存日程和地图；不要把临场找论文/路线完全依赖 venue Wi-Fi。",
            "action_en": "Download the app and save schedules/maps offline; do not rely entirely on venue Wi-Fi for last-minute paper or route lookup.",
            "source_name": "ICML registration update blog",
            "source_url": "https://blog.icml.cc/2026/05/24/icml-2026-registration-update-capacity-limits-and-what-attendees-need-to-know/",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "yes",
            "notes": "Official blog warns that venue wireless has limitations and may be degraded in crowded areas; SSID/password still need onsite confirmation.",
        },
        {
            "category": "food",
            "item_zh": "茶歇/零食标签与特殊餐",
            "item_en": "Break labels and special meals",
            "date_or_time_kst": "",
            "location_zh": "会场茶歇区域",
            "location_en": "Conference break areas",
            "action_zh": "有饮食限制者每次取餐前看标签；ICML 页提示没有 halal/kosher meal，需准备外部备选。",
            "action_en": "Attendees with dietary restrictions should check labels every time; ICML notes no halal/kosher meals, so prepare outside options.",
            "source_name": "ICML At the Conference",
            "source_url": "https://icml.cc/Conferences/2026/AtTheConference",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "yes",
            "notes": "Guide should phrase this as an onsite planning warning, not a complete Seoul food statement.",
        },
        {
            "category": "food",
            "item_zh": "午餐自理",
            "item_en": "Lunch is self-managed",
            "date_or_time_kst": "",
            "location_zh": "COEX / Starfield COEX Mall / 周边餐厅",
            "location_en": "COEX / Starfield COEX Mall / nearby restaurants",
            "action_zh": "不要默认会方提供 box lunch；高峰期优先错峰或去 Parnas/Starfield 地下动线。",
            "action_en": "Do not assume conference box lunches; avoid peak queues or use the Parnas/Starfield underground options.",
            "source_name": "ICML virtual site / At the Conference",
            "source_url": "https://icml.cc/virtual/2026/index.html",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "yes",
            "notes": "Official site notes AM/PM breaks with food, coffee, and tea, but not boxed lunch.",
        },
        {
            "category": "poster_author",
            "item_zh": "Poster 张贴规则",
            "item_en": "Poster hanging rules",
            "date_or_time_kst": "",
            "location_zh": "Hall A poster sessions",
            "location_en": "Hall A poster sessions",
            "action_zh": "只用会方提供的 approved tape；每张 poster 建议四角各一段；不要贴墙或非指定位置。",
            "action_en": "Use only conference-provided approved tape; use one piece per corner; do not hang posters on walls or outside designated boards.",
            "source_name": "ICML At the Conference / Poster Instructions",
            "source_url": "https://icml.cc/Conferences/2026/PosterInstructions",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "AtTheConference also says volunteers in Hall A provide the tape.",
        },
        {
            "category": "poster_author",
            "item_zh": "Poster 取件",
            "item_en": "Poster pickup",
            "date_or_time_kst": "Jul 7-9 09:00-18:00; Jul 10 07:30-12:30; Jul 11 07:30-12:30",
            "location_zh": "COEX East Gate 附近 Hall B2 poster pick-up area",
            "location_en": "Poster pickup area near Hall B2, East Gate, COEX",
            "action_zh": "使用官方 Foster 打印服务者，带确认邮件并在展示当天取件。",
            "action_en": "If using the official Foster printing service, bring the confirmation email and pick up on the presentation day.",
            "source_name": "ICML Poster Instructions",
            "source_url": "https://icml.cc/Conferences/2026/PosterInstructions",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include_for_authors",
            "needs_recheck": "yes",
            "notes": "Source contains a duplicated '7:30' in the Saturday line; keep as 07:30-12:30 and verify onsite.",
        },
        {
            "category": "poster_author",
            "item_zh": "Poster 尺寸",
            "item_en": "Poster sizes",
            "date_or_time_kst": "",
            "location_zh": "Hall A / workshop poster boards",
            "location_en": "Hall A / workshop poster boards",
            "action_zh": "Main Conference 建议 36in 高 x 48/60/72in 宽；Workshop 不超过 36in 高 x 24in 宽且需竖版。",
            "action_en": "Main Conference suggests 36in high by 48/60/72in wide; workshop posters must not exceed 36in high by 24in wide and must be portrait.",
            "source_name": "ICML Poster Instructions",
            "source_url": "https://icml.cc/Conferences/2026/PosterInstructions",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include_for_authors",
            "needs_recheck": "no",
            "notes": "",
        },
        {
            "category": "poster_author",
            "item_zh": "Poster metadata",
            "item_en": "Poster metadata",
            "date_or_time_kst": "Recommended at least one week before conference starts",
            "location_zh": "ICML poster page / My Stuff",
            "location_en": "ICML poster page / My Stuff",
            "action_zh": "作者可上传 virtual poster、thumbnail、topic、slide deck、project page；topic 用于 poster 位置分配。",
            "action_en": "Authors can upload virtual poster, thumbnail, topic, slide deck, and project page; topic is used for poster position assignment.",
            "source_name": "ICML Poster Instructions",
            "source_url": "https://icml.cc/Conferences/2026/PosterInstructions",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "include_for_authors",
            "needs_recheck": "no",
            "notes": "",
        },
        {
            "category": "venue_wayfinding",
            "item_zh": "ICML 官方 COEX floor map",
            "item_en": "ICML official COEX floor map",
            "date_or_time_kst": "",
            "location_zh": "COEX",
            "location_en": "COEX",
            "action_zh": "正式指南的会场图优先引用 ICML 官方 SVG，再叠加 Hall A、Hall B Foyer、Hall B1/B2、Auditorium 等锚点。",
            "action_en": "Use the ICML official SVG as the venue-map base, then overlay anchors such as Hall A, Hall B Foyer, Hall B1/B2, and Auditorium.",
            "source_name": "ICML COEX floor map SVG",
            "source_url": "https://media.icml.cc/Conferences/ICML2026/coex_map.svg",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "yes",
            "notes": "Onsite signage should still be checked for entrance and queue changes.",
        },
        {
            "category": "venue_wayfinding",
            "item_zh": "COEX 官方楼层图",
            "item_en": "COEX official floor plan",
            "date_or_time_kst": "",
            "location_zh": "COEX 1F-4F",
            "location_en": "COEX 1F-4F",
            "action_zh": "把 Hall A/B、Hall B Foyer、West/East Gate、2F Plaetz、3F Auditorium 作为会场地图标注重点。",
            "action_en": "Mark Hall A/B, Hall B Foyer, West/East Gate, 2F Plaetz, and 3F Auditorium as key map anchors.",
            "source_name": "COEX Facilities Floor Plan",
            "source_url": "https://www.coexcenter.com/facilities-floor-plan/",
            "source_type": "official_venue",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "yes",
            "notes": "Need combine with ICML's actual room assignments from official schedule/app.",
        },
        {
            "category": "sponsors_expo",
            "item_zh": "Exhibitor Sponsor Hall",
            "item_en": "Exhibitor Sponsor Hall",
            "date_or_time_kst": "Jul 7 11:00-19:00; Jul 8 09:00-18:00; Jul 9 09:00-18:00",
            "location_zh": "Hall B1",
            "location_en": "Hall B1",
            "action_zh": "把 Hall B1 当作招聘、产品 demo、infra/vendor 比较的主阵地；避开主会 poster 高峰。",
            "action_en": "Treat Hall B1 as the main recruiting, product-demo, and infra/vendor comparison area; avoid main-poster rush hours.",
            "source_name": "ICML sponsor list / virtual site",
            "source_url": "https://icml.cc/virtual/2026/sponsor_list",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "yes",
            "notes": "Final booth map should be refreshed from app or onsite signage.",
        },
        {
            "category": "sponsors_expo",
            "item_zh": "Expo talks / demos / workshops",
            "item_en": "Expo talks, demos, and workshops",
            "date_or_time_kst": "2026-07-06",
            "location_zh": "Auditorium, Hall B2/C/D1/D2, Grand Ballroom Foyer 等",
            "location_en": "Auditorium, Hall B2/C/D1/D2, Grand Ballroom Foyer, etc.",
            "action_zh": "把 7 月 6 日 Expo 作为比晚宴更稳定的公司技术入口，特别适合招聘/产品/研究合作线索。",
            "action_en": "Use July 6 Expo as a more reliable company-technology entry point than dinners, especially for recruiting, product, and collaboration leads.",
            "source_name": "ICML Expo events",
            "source_url": "https://icml.cc/virtual/2026/events/2026-Expo",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "yes",
            "notes": "Detailed event list may change; refresh before publishing daily guide.",
        },
        {
            "category": "venue_services",
            "item_zh": "Starfield COEX Mall 营业和客服",
            "item_en": "Starfield COEX Mall hours and customer center",
            "date_or_time_kst": "Mall 10:30-22:00; Customer Center 10:00-22:00",
            "location_zh": "513 Yeongdong-daero; B1 Live Plaza customer center",
            "location_en": "513 Yeongdong-daero; B1 Live Plaza customer center",
            "action_zh": "作为雨天、午餐、补给、失物、翻译/楼层咨询的默认点。",
            "action_en": "Use it as the default rainy-day, lunch, supplies, lost-and-found, interpretation, and floor-guide fallback.",
            "source_name": "VisitKorea Starfield COEX Mall",
            "source_url": "https://english.visitkorea.or.kr/svc/whereToGo/locIntrdn/rgnContentsView.do?vcontsId=73375",
            "source_type": "official_tourism",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "Operating hours vary by shop.",
        },
        {
            "category": "venue_services",
            "item_zh": "Starfield 信息台和轮椅/婴儿车",
            "item_en": "Starfield information desks and wheelchair/stroller rental",
            "date_or_time_kst": "Information desks 10:00-19:00",
            "location_zh": "COEX Mall 信息台 1/2",
            "location_en": "COEX Mall Information Desk 1/2",
            "action_zh": "需要轮椅、婴儿车、楼层咨询时可作为会场外备选。",
            "action_en": "Use as an off-conference backup for wheelchair, stroller, and floor-guide support.",
            "source_name": "VisitKorea Starfield COEX Mall",
            "source_url": "https://english.visitkorea.or.kr/svc/whereToGo/locIntrdn/rgnContentsView.do?vcontsId=73375",
            "source_type": "official_tourism",
            "confidence": "high",
            "guide_priority": "include",
            "needs_recheck": "no",
            "notes": "",
        },
        {
            "category": "food",
            "item_zh": "COEX East Gate 餐饮点",
            "item_en": "COEX East Gate restaurant option",
            "date_or_time_kst": "Mon-Thu & Sun 11:30-24:00; Fri-Sat 11:30-01:00",
            "location_zh": "COEX 1F East Gate",
            "location_en": "1st floor East Gate, COEX",
            "action_zh": "作为会场内较晚营业的多人约饭/啤酒备选。",
            "action_en": "Use as a late-opening onsite option for group meals or beer.",
            "source_name": "COEX Restaurants",
            "source_url": "https://www.coexcenter.com/catering-service/restaurants/",
            "source_type": "official_venue",
            "confidence": "medium",
            "guide_priority": "include",
            "needs_recheck": "yes",
            "notes": "Current COEX page lists Devil's Door details; verify crowding and exact service during ICML.",
        },
        {
            "category": "local_transport",
            "item_zh": "交通卡",
            "item_en": "Transit cards",
            "date_or_time_kst": "",
            "location_zh": "便利店、地铁站、机场等",
            "location_en": "Convenience stores, subway stations, airports, etc.",
            "action_zh": "落地后尽早准备 Tmoney/EZL/WOWPASS/Climate Card；适合地铁、公交和部分线下支付。",
            "action_en": "Get a Tmoney/EZL/WOWPASS/Climate Card early; useful for subway, bus, and some offline payments.",
            "source_name": "VisitKorea Transportation Cards",
            "source_url": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=140663",
            "source_type": "official_tourism",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "Cards can be purchased and charged at convenience stores nationwide.",
        },
        {
            "category": "local_transport",
            "item_zh": "Seoul 交通卡折扣",
            "item_en": "Seoul transit card discounts",
            "date_or_time_kst": "",
            "location_zh": "Seoul subway / buses",
            "location_en": "Seoul subway / buses",
            "action_zh": "使用交通卡并上下车刷卡，争取公交地铁换乘折扣。",
            "action_en": "Use and tap the transit card correctly to get bus/subway transfer discounts.",
            "source_name": "VisitSeoul Transportation",
            "source_url": "https://english.visitseoul.net/transportation",
            "source_type": "official_tourism",
            "confidence": "medium",
            "guide_priority": "include",
            "needs_recheck": "no",
            "notes": "Search snippet confirms KRW 100 and transfer discount details; page fetch was minimal.",
        },
        {
            "category": "local_essentials",
            "item_zh": "电源和插头",
            "item_en": "Power and plugs",
            "date_or_time_kst": "",
            "location_zh": "韩国全境",
            "location_en": "Korea",
            "action_zh": "带 Type C/F 两圆孔转换头；韩国标准为 220V/60Hz；检查设备是否支持 100-240V。",
            "action_en": "Bring Type C/F round-pin adapters; Korea uses 220V/60Hz; check whether devices support 100-240V.",
            "source_name": "VisitKorea Electricity & Communications",
            "source_url": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=140041",
            "source_type": "official_tourism",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "VisitKorea says adapters can be borrowed/purchased at hotels, airports, retail stores, duty-free shops, and convenience stores.",
        },
        {
            "category": "local_essentials",
            "item_zh": "紧急电话",
            "item_en": "Emergency calls",
            "date_or_time_kst": "24/7",
            "location_zh": "韩国全境",
            "location_en": "Korea",
            "action_zh": "报警 112；火警/急救 119；感染病 1339；旅游热线 +82-2-1330；失物 Lost112 +82-2-182。",
            "action_en": "Police 112; fire/medical 119; infectious disease 1339; travel hotline +82-2-1330; Lost112 +82-2-182.",
            "source_name": "VisitKorea Emergency Situations",
            "source_url": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=140042",
            "source_type": "official_tourism",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "1330 supports Korean, English, Japanese, Chinese, Russian, Vietnamese, Thai, and Indonesian.",
        },
        {
            "category": "local_essentials",
            "item_zh": "Seoul Free WiFi 和热线",
            "item_en": "Seoul Free WiFi and hotlines",
            "date_or_time_kst": "24/7 hotline for 1330",
            "location_zh": "Seoul",
            "location_en": "Seoul",
            "action_zh": "把 1330 旅游热线和 1345 immigration hotline 放到指南首页或 emergency card。",
            "action_en": "Put 1330 travel hotline and 1345 immigration hotline on the guide front page or emergency card.",
            "source_name": "Seoul Metropolitan Government",
            "source_url": "https://english.seoul.go.kr/policy/smart-city/seoul-free-wifi/",
            "source_type": "official_government",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "no",
            "notes": "Seoul page lists domestic/international numbers for 120, 1330, and 1345.",
        },
        {
            "category": "weather",
            "item_zh": "ICML 周天气风险",
            "item_en": "ICML week weather risk",
            "date_or_time_kst": "Forecast checked 2026-07-02 for Jul 7-12",
            "location_zh": "Seoul",
            "location_en": "Seoul",
            "action_zh": "按梅雨/闷热处理：带轻便雨具、可防水鞋、薄外套和水杯；尽量用 COEX/Starfield 室内动线。",
            "action_en": "Plan for monsoon-like humidity and rain: bring light rain gear, water-resistant shoes, a light layer, and a water bottle; prefer indoor COEX/Starfield routes.",
            "source_name": "Weather forecast",
            "source_url": "web.weather: Seoul forecast captured 2026-07-02 for Jul 7-12",
            "source_type": "weather_forecast",
            "confidence": "medium",
            "guide_priority": "must_include",
            "needs_recheck": "yes",
            "notes": "Forecast showed rain/thunderstorm risk and very humid conditions from Jul 7-12; update daily during conference week.",
        },
        {
            "category": "conference_tools",
            "item_zh": "ICML 官方 App",
            "item_en": "Official ICML app",
            "date_or_time_kst": "Install before arrival",
            "location_zh": "手机",
            "location_en": "Mobile phone",
            "action_zh": "会前安装 iOS/Android 官方 app；用于 QR code check-in、日程、本地保存和参会者聊天。",
            "action_en": "Install the official iOS/Android app before arriving; use it for QR-code check-in, schedule lookup, local saved schedules, and attendee chat.",
            "source_name": "ICML home / app store pages",
            "source_url": "https://icml.cc/Conferences/2026",
            "source_type": "app_store",
            "confidence": "high",
            "guide_priority": "must_include",
            "needs_recheck": "yes",
            "notes": "Android page: https://play.google.com/store/apps/details?id=com.atonyman.icml ; iOS page: https://apps.apple.com/us/app/icml/id6759976518",
        },
        {
            "category": "conference_tools",
            "item_zh": "Career Site",
            "item_en": "Career Site",
            "date_or_time_kst": "",
            "location_zh": "ICML 网站",
            "location_en": "ICML website",
            "action_zh": "想找工作/实习/industry connect 的参会者，注册后登录 Career Site 查看。",
            "action_en": "Attendees looking for jobs, internships, or industry connections should log into the Career Site after registration.",
            "source_name": "ICML Career Opportunities",
            "source_url": "https://icml.cc/careers/",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "include",
            "needs_recheck": "yes",
            "notes": "Page says paid registration is required to view job postings.",
        },
        {
            "category": "sponsors_expo",
            "item_zh": "Sponsor / Exhibitor 信息",
            "item_en": "Sponsor / exhibitor information",
            "date_or_time_kst": "Expo/Tutorial Day: 2026-07-06",
            "location_zh": "ICML Expo / sponsor area",
            "location_en": "ICML Expo / sponsor area",
            "action_zh": "把赞助商/booth 当作招聘、产品、研究合作路线；最终 booth list 和 booth map 需要会前再抓。",
            "action_en": "Treat sponsors/booths as recruiting, product, and research-collaboration routes; final booth list and map still need pre-conference refresh.",
            "source_name": "ICML sponsor information",
            "source_url": "https://icml.cc/sponsors/sponsorinfo",
            "source_type": "official",
            "confidence": "medium",
            "guide_priority": "include",
            "needs_recheck": "yes",
            "notes": "Sponsor page links to exhibitors portal; public page notes recruitment database access in sponsor levels.",
        },
        {
            "category": "official_socials",
            "item_zh": "官方 Socials / Mentoring 定位",
            "item_en": "Official socials and mentoring positioning",
            "date_or_time_kst": "",
            "location_zh": "ICML 官方日程",
            "location_en": "ICML official schedule",
            "action_zh": "官方 socials 更适合研究交流；商业宣传/招聘应归到 sponsor/expo 或外部 side events。",
            "action_en": "Official socials are intended for research connections; commercial promotion and recruiting should be treated as sponsor/expo or external side-event material.",
            "source_name": "ICML Call for Socials and Mentoring Forums",
            "source_url": "https://icml.cc/Conferences/2026/CallForSocials",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "include",
            "needs_recheck": "yes",
            "notes": "Useful for separating official social guide from company dinner guide.",
        },
        {
            "category": "visa_hotel",
            "item_zh": "签证邀请信",
            "item_en": "Visa invitation letter",
            "date_or_time_kst": "",
            "location_zh": "ICML 网站",
            "location_en": "ICML website",
            "action_zh": "只从 ICML 网站申请邀请信；不要用第三方 booking agency；需要先买 in-person registration。",
            "action_en": "Request invitation letters only from the ICML site; do not use third-party booking agencies; in-person registration is required.",
            "source_name": "ICML Visa Information",
            "source_url": "https://icml.cc/Conferences/2026/VisaInformation",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "include",
            "needs_recheck": "no",
            "notes": "ICML page says ICML cannot provide a Business Registration Certificate.",
        },
        {
            "category": "visa_hotel",
            "item_zh": "官方酒店预订",
            "item_en": "Official hotel booking",
            "date_or_time_kst": "",
            "location_zh": "ICML housing link",
            "location_en": "ICML housing link",
            "action_zh": "若还没订房，只走 ICML hotel page 的 Resiada 链接；不要被第三方会议酒店代理误导。",
            "action_en": "If still booking, use the Resiada link on the ICML hotel page; avoid third-party conference-hotel agents.",
            "source_name": "ICML Hotel Information",
            "source_url": "https://icml.cc/Conferences/2026/Hotels",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "include",
            "needs_recheck": "yes",
            "notes": "Availability changes quickly.",
        },
        {
            "category": "family",
            "item_zh": "未成年人和儿童照护",
            "item_en": "Minors and childcare",
            "date_or_time_kst": "",
            "location_zh": "ICML 会场",
            "location_en": "ICML venue",
            "action_zh": "14-17 岁可随注册 guardian 免费入场但需 waiver；4 个月至 13 岁 childcare 已关闭且无 onsite reservation。",
            "action_en": "Ages 14-17 may attend free with a registered guardian and waiver; childcare for ages 4 months to 13 years is closed with no onsite reservations.",
            "source_name": "ICML Attending with Children",
            "source_url": "https://icml.cc/Conferences/2026/ChildCare",
            "source_type": "official",
            "confidence": "high",
            "guide_priority": "include",
            "needs_recheck": "no",
            "notes": "Minors must remain with guardian and can attend only events without alcohol.",
        },
    ]


def local_essentials() -> list[dict[str, str]]:
    return [
        {
            "category": "within_5_min",
            "name_zh": "Starfield COEX Mall",
            "name_en": "Starfield COEX Mall",
            "korean_note": "스타필드 코엑스몰",
            "why_zh": "COEX 地下主补给区，吃饭、咖啡、书店、休息点、雨天动线都在这里。",
            "why_en": "Main underground supply zone for dining, coffee, bookstore, short breaks, and rain-safe movement.",
            "hours_or_timing": "10:30-22:00; shop hours vary",
            "location_zh": "COEX 地下连通，Samseong / Bongeunsa 均可达",
            "location_en": "Underground connection to COEX; accessible from Samseong / Bongeunsa",
            "guide_use_zh": "会场 5 分钟内补给 / 雨天默认路线",
            "guide_use_en": "Within-5-minute supplies / default rainy-day route",
            "source_name": "Starfield official",
            "source_url": "https://www.starfield.co.kr/coexmall/main.do",
            "confidence": "high",
            "needs_recheck": "yes",
            "notes": "Use mall-level hours only; individual store hours vary.",
        },
        {
            "category": "within_5_min",
            "name_zh": "Gourmet Street",
            "name_en": "Gourmet Street",
            "korean_note": "",
            "why_zh": "适合 3-6 人相对正式的约饭，覆盖 casual 到 restaurant。",
            "why_en": "Good for 3-6 person meals from casual dining to restaurants.",
            "hours_or_timing": "Mall hours 10:30-22:00; shop hours vary",
            "location_zh": "Starfield COEX Mall B1-1F",
            "location_en": "Starfield COEX Mall B1-1F",
            "guide_use_zh": "小组晚饭 / sponsor chat 备选",
            "guide_use_en": "Small-group dinner / sponsor-chat backup",
            "source_name": "Starfield Gourmet Street",
            "source_url": "https://www.starfield.co.kr/coexmall/cafeDining/gourmetStreet.do",
            "confidence": "high",
            "needs_recheck": "yes",
            "notes": "Reserve or go off-peak for dinner during conference week.",
        },
        {
            "category": "within_5_min",
            "name_zh": "City Air Tower Food Street",
            "name_en": "City Air Tower Food Street",
            "korean_note": "",
            "why_zh": "短午休效率高，适合快速吃饭后回 poster / oral。",
            "why_en": "Efficient for short lunch gaps before returning to posters or orals.",
            "hours_or_timing": "Mall hours 10:30-22:00; shop hours vary",
            "location_zh": "COEX / CALT 一侧地下",
            "location_en": "Underground on the COEX / CALT side",
            "guide_use_zh": "快速午饭",
            "guide_use_en": "Quick lunch",
            "source_name": "Starfield Food Street",
            "source_url": "https://www.starfield.co.kr/coexmall/cafeDining/foodStreet.do",
            "confidence": "high",
            "needs_recheck": "yes",
            "notes": "Expect queues at peak lunch time.",
        },
        {
            "category": "within_5_min",
            "name_zh": "Starfield Cafe 区",
            "name_en": "Starfield Cafe zone",
            "korean_note": "",
            "why_zh": "短聊、等人、会前咖啡；官方列出 Starbucks Reserve、Paul Bassett 等。",
            "why_en": "Coffee, short chats, and waiting point; official listings include Starbucks Reserve and Paul Bassett.",
            "hours_or_timing": "Mall hours 10:30-22:00; shop hours vary",
            "location_zh": "Starfield COEX Mall 内",
            "location_en": "Inside Starfield COEX Mall",
            "guide_use_zh": "咖啡 / 会面",
            "guide_use_en": "Coffee / meetup",
            "source_name": "Starfield Cafe",
            "source_url": "https://www.starfield.co.kr/coexmall/cafeDining/cafe.do",
            "confidence": "high",
            "needs_recheck": "yes",
            "notes": "Use for quick meetings, not quiet deep work.",
        },
        {
            "category": "within_5_min",
            "name_zh": "Starfield Library",
            "name_en": "Starfield Library",
            "korean_note": "",
            "why_zh": "好找，适合集合和短暂休息。",
            "why_en": "Easy landmark for meeting and short breaks.",
            "hours_or_timing": "10:30-22:00",
            "location_zh": "COEX Mall 中央",
            "location_en": "Central COEX Mall",
            "guide_use_zh": "集合点 / 休息点",
            "guide_use_en": "Meeting point / break point",
            "source_name": "Starfield official",
            "source_url": "https://www.starfield.co.kr/coexmall/main.do",
            "confidence": "high",
            "needs_recheck": "yes",
            "notes": "Busy and photo-heavy; not ideal for focused conversation.",
        },
        {
            "category": "within_5_min",
            "name_zh": "Parnas Mall",
            "name_en": "Parnas Mall",
            "korean_note": "",
            "why_zh": "Parnas / InterContinental 侧，适合比 COEX Mall 稍安静的饭局。",
            "why_en": "Parnas / InterContinental side option for somewhat quieter meals than COEX Mall.",
            "hours_or_timing": "10:00-22:00",
            "location_zh": "Grand InterContinental / Samseong Station 侧，地下连通",
            "location_en": "Grand InterContinental / Samseong Station side, underground connected",
            "guide_use_zh": "商务饭 / sponsor chat 备选",
            "guide_use_en": "Business meal / sponsor-chat backup",
            "source_name": "VisitKorea",
            "source_url": "https://english.visitkorea.or.kr/svc/whereToGo/locIntrdn/rgnContentsView.do?vcontsId=73474",
            "confidence": "high",
            "needs_recheck": "yes",
            "notes": "Individual restaurant hours and reservations still need live checks.",
        },
        {
            "category": "within_5_min",
            "name_zh": "Devil's Door, COEX East Gate",
            "name_en": "Devil's Door, COEX East Gate",
            "korean_note": "",
            "why_zh": "COEX 官方列 320 seats，适合较大组晚饭或啤酒。",
            "why_en": "COEX lists 320 seats; useful for larger group dinner or beer.",
            "hours_or_timing": "Sun-Thu 11:30-24:00; Fri-Sat 11:30-01:00",
            "location_zh": "COEX 1F East Gate",
            "location_en": "COEX 1F East Gate",
            "guide_use_zh": "大组约饭 / 晚间备选",
            "guide_use_en": "Large-group meal / evening backup",
            "source_name": "COEX Restaurants",
            "source_url": "https://www.coexcenter.com/catering-service/restaurants/",
            "confidence": "high",
            "needs_recheck": "yes",
            "notes": "Crowding and event-week availability should be checked.",
        },
        {
            "category": "within_5_min",
            "name_zh": "COEX-WTC 地下连通区",
            "name_en": "COEX-WTC underground connection",
            "korean_note": "",
            "why_zh": "可连 COEX Mall、会展中心、City Airport、银行、邮局、药店、百货和酒店。",
            "why_en": "Connects COEX Mall, convention center, City Airport, banks, post office, drugstores, department store, and hotels.",
            "hours_or_timing": "Facility dependent",
            "location_zh": "COEX / Trade Tower / Parnas 地下网络",
            "location_en": "COEX / Trade Tower / Parnas underground network",
            "guide_use_zh": "雨天动线",
            "guide_use_en": "Rain-safe route",
            "source_name": "WTC Seoul",
            "source_url": "https://wtcseoul.com/en/sub/trade.php",
            "confidence": "high",
            "needs_recheck": "no",
            "notes": "Prefer underground routes in heavy rain or heat.",
        },
        {
            "category": "within_5_min",
            "name_zh": "便利店",
            "name_en": "Convenience stores",
            "korean_note": "",
            "why_zh": "买水、零食、简单用品，也常用于 T-money 充值。",
            "why_en": "Water, snacks, simple supplies, and often T-money top-up.",
            "hours_or_timing": "Store dependent",
            "location_zh": "Starfield / Trade Center 周边",
            "location_en": "Around Starfield / Trade Center",
            "guide_use_zh": "补给",
            "guide_use_en": "Supplies",
            "source_name": "WTC Seoul",
            "source_url": "https://wtcseoul.com/en/sub/trade.php",
            "confidence": "medium",
            "needs_recheck": "yes",
            "notes": "Write as nearby availability, not as a specific 24-hour claim.",
        },
        {
            "category": "within_5_min",
            "name_zh": "药店 / 医务室",
            "name_en": "Pharmacy / medical room",
            "korean_note": "",
            "why_zh": "感冒药、创可贴、应急处理；Starfield 有医务室，正规药局需现场确认。",
            "why_en": "Cold medicine, bandages, and basic support; Starfield has a medical room, but formal pharmacy details need live checks.",
            "hours_or_timing": "Store/facility dependent",
            "location_zh": "Trade Center 周边 / Starfield 1F",
            "location_en": "Around Trade Center / Starfield 1F",
            "guide_use_zh": "药品和急救备选",
            "guide_use_en": "Medicine and first-aid backup",
            "source_name": "WTC Seoul / Starfield facilities",
            "source_url": "https://www.starfield.co.kr/coexmall/tenant/facility.do",
            "confidence": "medium",
            "needs_recheck": "yes",
            "notes": "Separate pharmacy from beauty drugstores; prescription medicine requires a proper pharmacy.",
        },
        {
            "category": "within_5_min",
            "name_zh": "Linko stationery",
            "name_en": "Linko stationery",
            "korean_note": "",
            "why_zh": "打印、胶带、笔、本子、名牌/海报应急。",
            "why_en": "Printing, tape, pens, notebooks, badge/poster emergencies.",
            "hours_or_timing": "Store dependent",
            "location_zh": "Trade Center 周边",
            "location_en": "Around Trade Center",
            "guide_use_zh": "打印 / 文具",
            "guide_use_en": "Printing / stationery",
            "source_name": "WTC Seoul",
            "source_url": "https://wtcseoul.com/en/sub/trade.php",
            "confidence": "medium",
            "needs_recheck": "yes",
            "notes": "Check hours the day before relying on it for poster or badge fixes.",
        },
        {
            "category": "within_5_min",
            "name_zh": "银行 / ATM",
            "name_en": "Banks / ATMs",
            "korean_note": "",
            "why_zh": "现金、银行卡问题、应急换钱。",
            "why_en": "Cash, card issues, and emergency exchange.",
            "hours_or_timing": "Bank hours / ATM dependent",
            "location_zh": "COEX / Trade Center 周边",
            "location_en": "Around COEX / Trade Center",
            "guide_use_zh": "现金和银行卡应急",
            "guide_use_en": "Cash and card backup",
            "source_name": "WTC Seoul",
            "source_url": "https://wtcseoul.com/en/sub/trade.php",
            "confidence": "medium",
            "needs_recheck": "yes",
            "notes": "For large exchange, airport or bank business hours are safer.",
        },
        {
            "category": "arrival_first",
            "name_zh": "Incheon Airport bank / exchange / ATM",
            "name_en": "Incheon Airport bank / exchange / ATM",
            "korean_note": "",
            "why_zh": "落地先解决韩元现金，比会场临时找换汇更稳。",
            "why_en": "Solve KRW cash on arrival instead of improvising near the venue.",
            "hours_or_timing": "Many counters 06:00-22:00; some 24H",
            "location_zh": "ICN T1/T2 到达 / 出发层",
            "location_en": "ICN T1/T2 arrival / departure floors",
            "guide_use_zh": "机场落地先办",
            "guide_use_en": "Handle on arrival",
            "source_name": "Incheon Airport",
            "source_url": "https://www.airport.kr/ap_en/1536/subview.do",
            "confidence": "high",
            "needs_recheck": "yes",
            "notes": "Counters vary by terminal and provider.",
        },
        {
            "category": "arrival_first",
            "name_zh": "SIM / eSIM / Wi-Fi roaming centers",
            "name_en": "SIM / eSIM / Wi-Fi roaming centers",
            "korean_note": "",
            "why_zh": "落地办 SIM/eSIM 或取 Wi-Fi 蛋，避免会场 Wi-Fi 不稳时失联。",
            "why_en": "Get SIM/eSIM or pocket Wi-Fi on arrival to avoid relying on venue Wi-Fi.",
            "hours_or_timing": "Most 06:00-22:00; selected counters 24H",
            "location_zh": "ICN T1/T2 到达层 / 出发层",
            "location_en": "ICN T1/T2 arrival / departure floors",
            "guide_use_zh": "机场落地先办",
            "guide_use_en": "Handle on arrival",
            "source_name": "Incheon Airport",
            "source_url": "https://www.airport.kr/ap_en/1546/subview.do",
            "confidence": "high",
            "needs_recheck": "yes",
            "notes": "Pre-order and airport pickup can reduce queue time.",
        },
        {
            "category": "arrival_first",
            "name_zh": "T-money / EZL / WOWPASS",
            "name_en": "T-money / EZL / WOWPASS",
            "korean_note": "",
            "why_zh": "地铁公交、部分便利店支付；会期最常用。",
            "why_en": "Subway, bus, and some convenience-store payments; highly useful during the week.",
            "hours_or_timing": "Convenience stores / stations / airport availability",
            "location_zh": "机场、地铁站、便利店",
            "location_en": "Airport, subway stations, convenience stores",
            "guide_use_zh": "交通卡",
            "guide_use_en": "Transit card",
            "source_name": "VisitKorea transportation cards",
            "source_url": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=140663",
            "confidence": "high",
            "needs_recheck": "no",
            "notes": "Top-up often requires cash; keep small KRW bills.",
        },
        {
            "category": "arrival_first",
            "name_zh": "COEX Limo Bus 6103",
            "name_en": "COEX Limo Bus 6103",
            "korean_note": "",
            "why_zh": "行李友好，直达 COEX City Airport / Samseong Exit 5。",
            "why_en": "Luggage-friendly direct route to COEX City Airport / Samseong Exit 5.",
            "hours_or_timing": "ICN to city 05:40-23:10; to airport 04:10-21:00",
            "location_zh": "ICN T1/T2 -> COEX，约 65 分钟，18,000 KRW",
            "location_en": "ICN T1/T2 -> COEX, about 65 minutes, KRW 18,000",
            "guide_use_zh": "机场到会场",
            "guide_use_en": "Airport to venue",
            "source_name": "COEX airport directions",
            "source_url": "https://www.coexcenter.com/directions-map-airport-2/",
            "confidence": "high",
            "needs_recheck": "yes",
            "notes": "Schedule, fare, and boarding location should be checked close to travel time.",
        },
        {
            "category": "evening_or_rain_backup",
            "name_zh": "Gangnam Station Underground Shopping Center",
            "name_en": "Gangnam Station Underground Shopping Center",
            "korean_note": "",
            "why_zh": "雨天备选、简单购物、地铁换乘后集合。",
            "why_en": "Rain-safe backup, quick shopping, and post-subway meeting point.",
            "hours_or_timing": "09:00-22:00",
            "location_zh": "Samseong Line 2 到 Gangnam",
            "location_en": "Line 2 from Samseong to Gangnam",
            "guide_use_zh": "雨天备选",
            "guide_use_en": "Rain backup",
            "source_name": "Visit Seoul",
            "source_url": "https://english.visitseoul.net/shopping/Gangnam-Station-Underground-Shopping-Center/ENP017740",
            "confidence": "high",
            "needs_recheck": "yes",
            "notes": "Better for shopping/waiting than formal dinner.",
        },
        {
            "category": "evening_or_rain_backup",
            "name_zh": "Gangnam / Sinnonhyeon 餐饮街区",
            "name_en": "Gangnam / Sinnonhyeon dining area",
            "korean_note": "",
            "why_zh": "厂商晚宴后续、多人晚饭、酒吧更集中。",
            "why_en": "Good for post-company-dinner continuation, group meals, and bars.",
            "hours_or_timing": "Store dependent",
            "location_zh": "COEX -> Gangnam / Sinnonhyeon，地铁或出租车",
            "location_en": "COEX -> Gangnam / Sinnonhyeon by subway or taxi",
            "guide_use_zh": "晚饭 / 夜间备选",
            "guide_use_en": "Dinner / night backup",
            "source_name": "Visit Gangnam",
            "source_url": "https://visitgangnam.net/en",
            "confidence": "medium",
            "needs_recheck": "yes",
            "notes": "Use Naver/Google live info for specific restaurants, queue, and private rooms.",
        },
    ]


def onsite_opportunities() -> list[dict[str, str]]:
    return [
        {
            "opportunity_type": "sponsor_index",
            "name": "ICML 2026 Sponsors",
            "host": "ICML",
            "date_time_kst": "All conference week",
            "location": "COEX / official sponsor pages",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/sponsor_list",
            "confidence": "high",
            "guide_use_zh": "做逛展优先级和公司索引；赞助商总表约 100 家。",
            "guide_use_en": "Use as the expo priority list and company index; sponsor list has about 100 organizations.",
            "priority": "P0",
        },
        {
            "opportunity_type": "career",
            "name": "ICML Career Opportunities",
            "host": "ICML / sponsors / exhibitors",
            "date_time_kst": "All conference week",
            "location": "ICML Careers login",
            "onsite": "hybrid",
            "source_url": "https://icml.cc/careers/",
            "confidence": "high",
            "guide_use_zh": "注册后必看；公开页不显示岗位详情。",
            "guide_use_en": "Must-check after registration; public page does not expose job details.",
            "priority": "P0",
        },
        {
            "opportunity_type": "career",
            "name": "ICML Recruitment Database",
            "host": "ICML sponsors / exhibitors",
            "date_time_kst": "All conference week",
            "location": "ICML Careers / sponsor channels",
            "onsite": "hybrid",
            "source_url": "https://icml.cc/sponsors/sponsorinfo",
            "confidence": "high",
            "guide_use_zh": "提醒找工作的人先登录 careers，不要只靠线下搭讪。",
            "guide_use_en": "Tell job seekers to log into careers first instead of relying only on hallway conversations.",
            "priority": "P0",
        },
        {
            "opportunity_type": "career",
            "name": "Dedicated interview rooms",
            "host": "Diamond / Platinum sponsors",
            "date_time_kst": "By reservation",
            "location": "COEX",
            "onsite": "yes",
            "source_url": "https://icml.cc/sponsors/sponsorinfo",
            "confidence": "high",
            "guide_use_zh": "对 Diamond/Platinum 目标公司提前约面。",
            "guide_use_en": "Pre-book interviews with target Diamond/Platinum sponsors.",
            "priority": "P1",
        },
        {
            "opportunity_type": "expo",
            "name": "Expo Talks, Demos, Workshops",
            "host": "ICML / sponsors",
            "date_time_kst": "Mon Jul 6, 2026",
            "location": "Auditorium, Halls B2/C/D1/D2, Grand Ballroom Foyer",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/events/2026-Expo",
            "confidence": "high",
            "guide_use_zh": "比晚宴更稳定的公司技术入口；适合招聘、产品、研究合作线索。",
            "guide_use_en": "More reliable than dinner lists for company tech entry points, recruiting, product, and collaboration leads.",
            "priority": "P0",
        },
        {
            "opportunity_type": "expo_talk",
            "name": "Multi-Agent System Design and Evaluation for Quantitative Finance",
            "host": "Jump Trading",
            "date_time_kst": "Mon Jul 6 08:00-09:00",
            "location": "Hall D1",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/75722",
            "confidence": "high",
            "guide_use_zh": "量化 + multi-agent 方向重点看。",
            "guide_use_en": "High-value for quant + multi-agent interests.",
            "priority": "P1",
        },
        {
            "opportunity_type": "expo_workshop",
            "name": "Reliable and Efficient LLM Outputs with Mellea + Granite OSS Libraries",
            "host": "IBM-related",
            "date_time_kst": "Mon Jul 6 16:00-19:00",
            "location": "Auditorium",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/75711",
            "confidence": "high",
            "guide_use_zh": "开源 LLM infra / enterprise AI 实操场。",
            "guide_use_en": "Useful for open-source LLM infrastructure and enterprise AI practice.",
            "priority": "P1",
        },
        {
            "opportunity_type": "expo_demo",
            "name": "Xiaomi GUI Agent",
            "host": "Xiaomi",
            "date_time_kst": "Mon Jul 6 12:30-14:30",
            "location": "Grand Ballroom Foyer",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/75720",
            "confidence": "high",
            "guide_use_zh": "手机 GUI agent / device AI 方向可看。",
            "guide_use_en": "Useful for mobile GUI agents and device AI.",
            "priority": "P1",
        },
        {
            "opportunity_type": "expo_demo",
            "name": "AI for International E-Commerce",
            "host": "Alibaba ecosystem: AliExpress, Lazada, AIDC",
            "date_time_kst": "Mon Jul 6 12:30-14:30",
            "location": "Grand Ballroom Foyer",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/75719",
            "confidence": "high",
            "guide_use_zh": "电商推荐、购物 agent、供应链模型方向可看。",
            "guide_use_en": "Useful for e-commerce recommendation, shopping agents, and supply-chain models.",
            "priority": "P1",
        },
        {
            "opportunity_type": "mentorship",
            "name": "RAI Mentoring Circle: Responsible AI for Early Career AI Researchers",
            "host": "ICML Mentorship",
            "date_time_kst": "Mon Jul 6 13:00-17:00",
            "location": "ASEM Ballroom 201-203",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/mentorship/80259",
            "confidence": "high",
            "guide_use_zh": "early-career / responsible AI 单独推荐。",
            "guide_use_en": "Recommended for early-career and responsible-AI networking.",
            "priority": "P1",
        },
        {
            "opportunity_type": "reception",
            "name": "Welcome Reception",
            "host": "ICML",
            "date_time_kst": "Tue Jul 7 17:45-19:00",
            "location": "COEX first/second/third floor",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/reception/67263",
            "confidence": "high",
            "guide_use_zh": "官方社交主场，适合放每日行程。",
            "guide_use_en": "Main official social anchor; include in the daily route.",
            "priority": "P0",
        },
        {
            "opportunity_type": "affinity",
            "name": "LatinX in AI Workshop",
            "host": "LatinX in AI",
            "date_time_kst": "Tue Jul 7 08:00-17:00",
            "location": "Room 300",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/affinity-event/54097",
            "confidence": "high",
            "guide_use_zh": "diversity/community 版块。",
            "guide_use_en": "Diversity/community route.",
            "priority": "P2",
        },
        {
            "opportunity_type": "affinity",
            "name": "WiML Symposium at ICML 2026",
            "host": "Women in Machine Learning",
            "date_time_kst": "Wed Jul 8 08:00-17:00",
            "location": "Room E1-E4, 3rd Floor",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/affinity-event/54055",
            "confidence": "high",
            "guide_use_zh": "women/diversity/networking 必收。",
            "guide_use_en": "High-value women/diversity/networking event.",
            "priority": "P1",
        },
        {
            "opportunity_type": "affinity_poster",
            "name": "WiML, Muslims in ML, LatinX, GlobalSouthML Poster Session",
            "host": "Affinity groups",
            "date_time_kst": "Wed Jul 8 19:00-21:00",
            "location": "Hall A",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/affinity-poster-session/68481",
            "confidence": "high",
            "guide_use_zh": "适合晚间替代外部饭局。",
            "guide_use_en": "Good evening alternative to external dinners.",
            "priority": "P1",
        },
        {
            "opportunity_type": "affinity",
            "name": "GlobalSouthML @ ICML 2026",
            "host": "GlobalSouthML",
            "date_time_kst": "Thu Jul 9 08:00-17:00",
            "location": "Room E1-E4, 3rd Floor",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/affinity-event/54098",
            "confidence": "high",
            "guide_use_zh": "global south / community。",
            "guide_use_en": "Global South / community route.",
            "priority": "P2",
        },
        {
            "opportunity_type": "affinity",
            "name": "The 6th Muslims in ML Workshop",
            "host": "MusIML",
            "date_time_kst": "Thu Jul 9 08:00-17:00",
            "location": "Room 300",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/affinity-event/54056",
            "confidence": "high",
            "guide_use_zh": "inclusion/community。",
            "guide_use_en": "Inclusion/community route.",
            "priority": "P2",
        },
        {
            "opportunity_type": "social",
            "name": "Bridging Research and Open-Source",
            "host": "ICML Social",
            "date_time_kst": "Wed Jul 8 19:00-21:00",
            "location": "Room E1-E4",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/social/80676",
            "confidence": "high",
            "guide_use_zh": "开源社区 networking。",
            "guide_use_en": "Open-source community networking.",
            "priority": "P1",
        },
        {
            "opportunity_type": "social",
            "name": "How to Network at an AI Conference",
            "host": "ICML Social",
            "date_time_kst": "Wed Jul 8 19:00-21:00",
            "location": "ASEM Ballroom 201-203",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/social/80674",
            "confidence": "high",
            "guide_use_zh": "新手逛会指南强推荐。",
            "guide_use_en": "Strong recommendation for first-time conference goers.",
            "priority": "P0",
        },
        {
            "opportunity_type": "social",
            "name": "Robot Learning Social",
            "host": "ICML Social",
            "date_time_kst": "Wed Jul 8 19:00-21:00",
            "location": "Room 300",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/social/80675",
            "confidence": "high",
            "guide_use_zh": "robotics 方向聚集点。",
            "guide_use_en": "Robotics networking anchor.",
            "priority": "P1",
        },
        {
            "opportunity_type": "social",
            "name": "Cooperative AI",
            "host": "ICML Social",
            "date_time_kst": "Thu Jul 9 19:00-21:00",
            "location": "Room E5-E6",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/social/80681",
            "confidence": "high",
            "guide_use_zh": "AI safety / multi-agent 社区。",
            "guide_use_en": "AI safety / multi-agent community.",
            "priority": "P1",
        },
        {
            "opportunity_type": "town_hall",
            "name": "Town Hall",
            "host": "ICML",
            "date_time_kst": "Thu Jul 9 14:30-15:30",
            "location": "Hall C",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/town-hall/67275",
            "confidence": "high",
            "guide_use_zh": "了解组织方向、提问、找社群入口。",
            "guide_use_en": "Understand conference direction, ask questions, and find community entry points.",
            "priority": "P2",
        },
        {
            "opportunity_type": "recruiting_lead",
            "name": "Jane Street",
            "host": "Jane Street",
            "date_time_kst": "All conference week",
            "location": "Sponsor / expo / careers",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/sponsor_list",
            "confidence": "high",
            "guide_use_zh": "Diamond sponsor；官方 blurb 明确招聘取向。",
            "guide_use_en": "Diamond sponsor; official blurb signals recruiting interest.",
            "priority": "P1",
        },
        {
            "opportunity_type": "recruiting_lead",
            "name": "IMC",
            "host": "IMC",
            "date_time_kst": "All conference week",
            "location": "Sponsor / expo / careers",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/sponsor_list",
            "confidence": "high",
            "guide_use_zh": "Platinum sponsor；明确关注 PhD 和 industry candidates。",
            "guide_use_en": "Platinum sponsor; explicitly interested in PhD and industry candidates.",
            "priority": "P1",
        },
        {
            "opportunity_type": "recruiting_lead",
            "name": "Preference Model",
            "host": "Preference Model",
            "date_time_kst": "All conference week",
            "location": "Sponsor / expo / careers",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/sponsor_list",
            "confidence": "high",
            "guide_use_zh": "Silver sponsor；官方 blurb 明确 hiring researchers and engineers。",
            "guide_use_en": "Silver sponsor; official blurb explicitly says hiring researchers and engineers.",
            "priority": "P1",
        },
        {
            "opportunity_type": "career_or_mentoring",
            "name": "MATS Research",
            "host": "MATS Research",
            "date_time_kst": "All conference week",
            "location": "Sponsor / expo / careers",
            "onsite": "yes",
            "source_url": "https://icml.cc/virtual/2026/sponsor_list",
            "confidence": "high",
            "guide_use_zh": "AI alignment early researcher / mentors 线索。",
            "guide_use_en": "AI alignment early-researcher and mentor lead.",
            "priority": "P2",
        },
    ]


def checklist() -> list[dict[str, str]]:
    return [
        {
            "phase": "before_departure",
            "task_zh": "安装 ICML app，并确认能访问注册邮箱里的 receipt / QR code。",
            "task_en": "Install the ICML app and confirm access to the registration receipt / QR code in email.",
            "why_zh": "用于现场 check-in、日程和聊天。",
            "why_en": "Needed for check-in, schedule updates, and attendee chat.",
            "source_url": "https://play.google.com/store/apps/details?hl=en_US&id=com.atonyman.icml",
            "priority": "P0",
        },
        {
            "phase": "before_departure",
            "task_zh": "在官方 virtual site 里 bookmark 重点 papers / sessions，并导出或离线保存个人日程。",
            "task_en": "Bookmark key papers/sessions on the official virtual site and export or save the personal schedule offline.",
            "why_zh": "官方提醒会场 Wi-Fi 在拥挤区域可能不稳定。",
            "why_en": "Official guidance warns that venue Wi-Fi may be unreliable in crowded areas.",
            "source_url": "https://blog.icml.cc/2026/05/24/icml-2026-registration-update-capacity-limits-and-what-attendees-need-to-know/",
            "priority": "P0",
        },
        {
            "phase": "before_departure",
            "task_zh": "确认 Registration Desk 时间：7 月 5 日 14:00-19:30；7 月 6 日 07:00-18:00；7 月 7-9 日 07:30-18:00；7 月 10 日 07:30-16:00；7 月 11 日 07:30-12:00。",
            "task_en": "Confirm Registration Desk hours: Jul 5 14:00-19:30; Jul 6 07:00-18:00; Jul 7-9 07:30-18:00; Jul 10 07:30-16:00; Jul 11 07:30-12:00.",
            "why_zh": "Help Desk 时间跟注册台一致，且 workshop-only badge 从 7 月 9 日 16:00 开始领取。",
            "why_en": "Help Desk follows registration hours, and workshop-only badge pickup starts Jul 9 at 16:00.",
            "source_url": "https://icml.cc/virtual/2026/calendar?filter_events=Registration%20Desk&filter_rooms=",
            "priority": "P0",
        },
        {
            "phase": "before_departure",
            "task_zh": "学生票参会者准备学生证；所有人检查胸牌姓名/机构信息。",
            "task_en": "Student-rate attendees should carry student ID; everyone should check badge name/institution details.",
            "why_zh": "学生证和身份信息会影响 check-in。",
            "why_en": "Student ID and profile details affect check-in.",
            "source_url": "https://icml.cc/FAQ",
            "priority": "P0",
        },
        {
            "phase": "before_departure",
            "task_zh": "带 Type C/F 转换头，确认电脑/手机充电器支持 220V/60Hz。",
            "task_en": "Bring Type C/F adapters and confirm laptop/phone chargers support 220V/60Hz.",
            "why_zh": "韩国电压和插座与美国/英国/新加坡等常见插头不同。",
            "why_en": "Korea's voltage and outlets differ from US/UK/Singapore-style plugs.",
            "source_url": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=140041",
            "priority": "P0",
        },
        {
            "phase": "arrival_day",
            "task_zh": "购买或充值 Tmoney/EZL/WOWPASS/Climate Card，并准备少量现金。",
            "task_en": "Buy or top up Tmoney/EZL/WOWPASS/Climate Card and keep some cash.",
            "why_zh": "地铁/公交/便利店支付和换乘折扣更顺。",
            "why_en": "Makes subway/bus/convenience-store payments and transfer discounts easier.",
            "source_url": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=140663",
            "priority": "P0",
        },
        {
            "phase": "arrival_day",
            "task_zh": "机场先处理 SIM/eSIM/Wi-Fi、少量韩元现金和 6103 机场巴士/地铁路线。",
            "task_en": "At the airport, handle SIM/eSIM/Wi-Fi, small KRW cash, and the 6103 airport bus or subway route.",
            "why_zh": "比到 COEX 后临时找网络、换汇和交通方案更稳。",
            "why_en": "More reliable than improvising network, cash, and transport after reaching COEX.",
            "source_url": "https://www.coexcenter.com/directions-map-airport-2/",
            "priority": "P0",
        },
        {
            "phase": "arrival_day",
            "task_zh": "到 COEX 后先定位 Hall B Foyer、Hall A、East/West Gate、2F Plaetz。",
            "task_en": "At COEX, first locate Hall B Foyer, Hall A, East/West Gate, and 2F Plaetz.",
            "why_zh": "这些覆盖 help desk、poster、医疗、寄存和出入口。",
            "why_en": "These cover help desk, posters, medical office, luggage check, and entrances.",
            "source_url": "https://icml.cc/Conferences/2026/AtTheConference",
            "priority": "P0",
        },
        {
            "phase": "daily",
            "task_zh": "每天早上检查天气；雨天优先走 COEX/Starfield 室内动线。",
            "task_en": "Check weather each morning; use COEX/Starfield indoor routes on rainy days.",
            "why_zh": "7 月 7-12 日预报显示高湿、降雨和雷阵雨风险。",
            "why_en": "The Jul 7-12 forecast shows humid conditions with rain/thunderstorm risk.",
            "source_url": "web.weather: Seoul forecast captured 2026-07-02 for Jul 7-12",
            "priority": "P0",
        },
        {
            "phase": "daily",
            "task_zh": "离开酒店前检查胸牌；离开会场后取下胸牌。",
            "task_en": "Check badge before leaving the hotel; remove badge offsite.",
            "why_zh": "无胸牌不能入场，场外佩戴胸牌也不必要。",
            "why_en": "Badge is required for entry and unnecessary offsite.",
            "source_url": "https://icml.cc/FAQ",
            "priority": "P0",
        },
        {
            "phase": "authors",
            "task_zh": "Poster 作者确认 session、poster number、poster 尺寸、取件时间和 Hall A 张贴规则。",
            "task_en": "Poster authors should confirm session, poster number, poster size, pickup time, and Hall A hanging rules.",
            "why_zh": "取件和张贴规则非常具体，错过会影响展示。",
            "why_en": "Pickup and hanging rules are specific and can affect presentation.",
            "source_url": "https://icml.cc/Conferences/2026/PosterInstructions",
            "priority": "P0",
        },
        {
            "phase": "career_or_sponsors",
            "task_zh": "找工作/合作的人先登录 ICML Careers，再按 sponsor list 和 Expo events 排路线。",
            "task_en": "For jobs or collaborations, log into ICML Careers first, then plan routes from the sponsor list and Expo events.",
            "why_zh": "官方 Careers 和 Expo 比外部晚宴更稳定，且部分岗位/面试机会只对注册参会者开放。",
            "why_en": "Official Careers and Expo are more stable than external dinners, and some postings/interviews are registration-gated.",
            "source_url": "https://icml.cc/careers/",
            "priority": "P1",
        },
        {
            "phase": "daily",
            "task_zh": "把 112、119、1330、Lost112 号码存到手机。",
            "task_en": "Save 112, 119, 1330, and Lost112 on the phone.",
            "why_zh": "紧急、医疗、旅游热线、失物查询可快速使用。",
            "why_en": "Enables quick access to emergency, medical, tourist hotline, and lost-item support.",
            "source_url": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=140042",
            "priority": "P0",
        },
        {
            "phase": "evening_events",
            "task_zh": "所有 Luma guests-only 活动报名通过后，把精确地址替换进地图和路线链接。",
            "task_en": "After RSVP approval for guests-only Luma events, replace map and route links with the exact address.",
            "why_zh": "公开页只到区域级，不能当正式会场。",
            "why_en": "Public pages expose only an area, not the final venue.",
            "source_url": "data/processed/icml2026_side_events.csv",
            "priority": "P0",
        },
    ]


def backlog() -> list[dict[str, str]]:
    return [
        {
            "topic": "Registration desk hours",
            "why_collect": "Public calendar lists hours, but onsite queue layout and late changes may affect arrival planning.",
            "suggested_source": "ICML app, onsite signage, attendee email, AtTheConference page refresh",
            "status": "needs_recheck",
            "owner_note": "Current captured hours: Jul 5 14:00-19:30; Jul 6 07:00-18:00; Jul 7-9 07:30-18:00; Jul 10 07:30-16:00; Jul 11 07:30-12:00.",
        },
        {
            "topic": "Wi-Fi SSID / password",
            "why_collect": "High-value for guide front page, but likely only disclosed onsite or by email/app.",
            "suggested_source": "ICML app, badge packet, onsite signage, registration desk",
            "status": "needs_onsite",
            "owner_note": "Do not invent or use old-year Wi-Fi names.",
        },
        {
            "topic": "Sponsor / exhibitor booth map",
            "why_collect": "Useful for company route, recruiting, swag, infra/product vendor comparison.",
            "suggested_source": "ICML exhibitors portal, official app, onsite map",
            "status": "needs_recheck",
            "owner_note": "Public sponsor portal loaded via JavaScript; use browser/app if needed.",
        },
        {
            "topic": "Exact side-event addresses",
            "why_collect": "Many Luma events publish only obfuscated locations until RSVP approval.",
            "suggested_source": "Individual RSVP confirmation pages/emails",
            "status": "needs_private_confirmation",
            "owner_note": "Keep public guide at area level; use private copy for personal navigation.",
        },
        {
            "topic": "Room-level official map",
            "why_collect": "COEX official floor plan is venue-level; ICML room allocation should be overlaid.",
            "suggested_source": "ICML official app, virtual schedule pages, printed program",
            "status": "needs_recheck",
            "owner_note": "Combine with MapLibre/venue SVG only after official room mapping is stable.",
        },
        {
            "topic": "Nearby coffee and breakfast shortlist",
            "why_collect": "Useful for morning meetings and sponsor chats, but shop hours change quickly.",
            "suggested_source": "Starfield/Parnas official store pages, Google Maps live hours",
            "status": "nice_to_have",
            "owner_note": "Prefer zones over specific shops unless official hours are stable.",
        },
        {
            "topic": "Printing and pharmacy exact hours",
            "why_collect": "Useful for poster/badge emergencies and medicine, but WTC only confirms nearby availability.",
            "suggested_source": "Starfield store pages, Linko official listing, Naver/Google live hours, onsite walk-through",
            "status": "needs_recheck",
            "owner_note": "Keep current guide at category level until exact shop hours are confirmed.",
        },
        {
            "topic": "Company dinner private locations",
            "why_collect": "Useful for personal routing, but many are invite-only or released after RSVP approval.",
            "suggested_source": "RSVP confirmation email, sponsor Slack/Discord/email, Luma guest view",
            "status": "needs_private_confirmation",
            "owner_note": "Do not publish private addresses in the public guide.",
        },
        {
            "topic": "Daily weather update",
            "why_collect": "Seoul July forecast changes quickly; rain/heat affects routes and clothing.",
            "suggested_source": "Weather app / Korea Meteorological Administration / web.weather",
            "status": "daily_refresh",
            "owner_note": "Update morning of each conference day.",
        },
    ]


def main() -> None:
    write_csv(PRACTICAL_OUT, practical_info())
    write_csv(CHECKLIST_OUT, checklist())
    write_csv(BACKLOG_OUT, backlog())
    write_csv(LOCAL_ESSENTIALS_OUT, local_essentials())
    write_csv(ONSITE_OPPORTUNITIES_OUT, onsite_opportunities())
    print(f"Wrote {len(practical_info())} practical rows -> {PRACTICAL_OUT.relative_to(ROOT)}")
    print(f"Wrote {len(checklist())} checklist rows -> {CHECKLIST_OUT.relative_to(ROOT)}")
    print(f"Wrote {len(backlog())} backlog rows -> {BACKLOG_OUT.relative_to(ROOT)}")
    print(f"Wrote {len(local_essentials())} local essential rows -> {LOCAL_ESSENTIALS_OUT.relative_to(ROOT)}")
    print(f"Wrote {len(onsite_opportunities())} onsite opportunity rows -> {ONSITE_OPPORTUNITIES_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
